import{a as h,S as L,i as d}from"./assets/vendor-CNqCr-V-.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();function b(r){const s="https://pixabay.com/api/",n="53365045-d30e2460a35774e20f4e732a7",a=new URLSearchParams({key:n,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0});return h.get(`${s}?${a}`).then(e=>e.data)}const p=document.querySelector(".gallery"),i=document.querySelector(".loader"),f="is-shown";let o=null;function S(){o?o.refresh():o=new L(".gallery a",{captionsData:"alt",captionDelay:250})}function v(r){if(!Array.isArray(r)||r.length===0)return;const s=r.map(({webformatURL:n,largeImageURL:a,tags:e,likes:t,views:l,comments:g,downloads:y})=>`<li class="gallery-item">
          <a class="gallery-link" href="${a}">
            <img class="gallery-image" src="${n}" alt="${e}" loading="lazy" />
          </a>
          <div class="image-stats">
            <p class="stat">Likes <span>${t}</span></p>
            <p class="stat">Views <span>${l}</span></p>
            <p class="stat">Comments <span>${g}</span></p>
            <p class="stat">Downloads <span>${y}</span></p>
          </div>
        </li>`).join("");p.insertAdjacentHTML("beforeend",s),S()}function w(){p.innerHTML="",o&&(o.destroy(),o=null)}function A(){i&&(i.classList.add(f),i.setAttribute("aria-hidden","false"))}function q(){i&&(i.classList.remove(f),i.setAttribute("aria-hidden","true"))}const c=document.querySelector(".form"),u=c.querySelector("button[type=submit]"),m=c.querySelector('input[name="search-text"]');u.disabled=!0;m.addEventListener("input",r=>{u.disabled=r.target.value.trim()===""});c.addEventListener("submit",r=>{r.preventDefault();const s=m.value.trim();if(!s){d.warning({title:"Warning",message:"Please enter a search query",position:"topRight"});return}w(),A(),u.disabled=!0,b(s).then(n=>{const a=n.hits;if(!a.length){d.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}v(a)}).catch(()=>{d.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}).finally(()=>{q(),c.reset(),u.disabled=!0})});
//# sourceMappingURL=index.js.map
